# Site settings
title: For the love of machines
email: Kriish.hate1@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

twitter_username: username
github_username: KriishAhate

# Theme (Option A: gem-based Minimal Mistakes)
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

search: true
timezone: America/New_York

# Collections
collections:
  carshows:
    output: true
    permalink: /carshows/:title/
  roadtrips:
    output: true
    permalink: /roadtrips/:title/

# Build settings
markdown: kramdown

# Output
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages
  - _carshows
  - _roadtrips

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author
author:
  name   : "Kriish Hate"
  avatar : "/assets/images/profile.jpg"
  bio    : "Fueled by curiosity, driven by machines â€” engineer, maker, builder, and historian."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://kriishahate.github.io/Portfolio-Site/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KriishAHate"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KriishAHate"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: carshows
    values:
      layout: single
      classes: wide
      entries_layout: grid

  - scope:
      path: ""
      type: roadtrips
    values:
      layout: single
      classes: wide
      entries_layout: grid

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
